title: nyamsprod's notes
email: nyamsprod@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Not a single one of your ancestors died young. They all copulated at least once.
baseurl: ""
url: "https://nyamsprod.com"
twitter_username: nyamsprod
github_username:  nyamsprod

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist

exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor
